CREATE TABLE IF NOT EXISTS `weed_plants` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `coords` LONGTEXT NOT NULL,
  `model` VARCHAR(64) NOT NULL,
  `label` VARCHAR(64) DEFAULT NULL,
  `stage` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `health` SMALLINT UNSIGNED NOT NULL DEFAULT 100,
  `food` SMALLINT UNSIGNED NOT NULL DEFAULT 100,
  `water` SMALLINT UNSIGNED NOT NULL DEFAULT 100,
  `progress` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `sort` VARCHAR(32) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_sort` (`sort`),
  KEY `idx_stage` (`stage`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
